// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrwyyvWbWJYsuiyZC2Boec4lK_PEylb1U',
    appId: '1:494984339519:web:01d819bbd8603355b0588a',
    messagingSenderId: '494984339519',
    projectId: 'kursovoi-bb2ce',
    authDomain: 'kursovoi-bb2ce.firebaseapp.com',
    storageBucket: 'kursovoi-bb2ce.firebasestorage.app',
    measurementId: 'G-LQ15WD4JZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnx912ymZwc8wOHHWET3CWkUFSUBaiGk',
    appId: '1:494984339519:android:78fd24947f1e7d5db0588a',
    messagingSenderId: '494984339519',
    projectId: 'kursovoi-bb2ce',
    storageBucket: 'kursovoi-bb2ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_A7hd2JcY7izLBfwDww4zFjc0pM_9S1Y',
    appId: '1:494984339519:ios:b5773491771cc228b0588a',
    messagingSenderId: '494984339519',
    projectId: 'kursovoi-bb2ce',
    storageBucket: 'kursovoi-bb2ce.firebasestorage.app',
    iosClientId: '494984339519-r9gnb2jiaanvhldtdgp1h82jvg0reu6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.kursovoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_A7hd2JcY7izLBfwDww4zFjc0pM_9S1Y',
    appId: '1:494984339519:ios:b5773491771cc228b0588a',
    messagingSenderId: '494984339519',
    projectId: 'kursovoi-bb2ce',
    storageBucket: 'kursovoi-bb2ce.firebasestorage.app',
    iosClientId: '494984339519-r9gnb2jiaanvhldtdgp1h82jvg0reu6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.kursovoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrwyyvWbWJYsuiyZC2Boec4lK_PEylb1U',
    appId: '1:494984339519:web:fbf4b82bf1a9fe93b0588a',
    messagingSenderId: '494984339519',
    projectId: 'kursovoi-bb2ce',
    authDomain: 'kursovoi-bb2ce.firebaseapp.com',
    storageBucket: 'kursovoi-bb2ce.firebasestorage.app',
    measurementId: 'G-34TRSSJPVE',
  );
}
